import type { PrismaClient } from "@prisma/client";

type ExerciseInput = {
  slug: string;
  name: string;
  description: string;
  instructions: string;
  primaryMuscle:
    | "CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS"
    | "CORE" | "GLUTES" | "QUADS" | "HAMSTRINGS" | "CALVES" | "FULL_BODY" | "CARDIO";
  secondaryMuscles: ExerciseInput["primaryMuscle"][];
  equipment:
    | "BODYWEIGHT" | "DUMBBELL" | "BARBELL" | "RESISTANCE_BAND" | "PULL_UP_BAR"
    | "BENCH" | "KETTLEBELL" | "CABLE_MACHINE" | "SMITH_MACHINE"
    | "PUNCHING_BAG" | "JUMP_ROPE" | "BACKPACK" | "MAT";
  category:
    | "STRENGTH" | "HYPERTROPHY" | "CONDITIONING" | "MOBILITY" | "BOXING"
    | "CALISTHENICS" | "FULL_BODY" | "UPPER" | "LOWER" | "PUSH" | "PULL" | "LEGS" | "CORE";
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  isBoxing?: boolean;
};

const EXERCISES: ExerciseInput[] = [
  // -----------------------  HOME / BODYWEIGHT  -----------------------
  {
    slug: "pushup",
    name: "Push-Up",
    description: "Classic upper-body pressing pattern that builds chest, shoulders and triceps.",
    instructions:
      "Plank position, hands under shoulders. Brace core, lower chest to within an inch of the floor, drive back up.",
    primaryMuscle: "CHEST",
    secondaryMuscles: ["TRICEPS", "SHOULDERS", "CORE"],
    equipment: "BODYWEIGHT",
    category: "PUSH",
    difficulty: "BEGINNER",
  },
  {
    slug: "diamond-pushup",
    name: "Diamond Push-Up",
    description: "Triceps-dominant push-up variation.",
    instructions: "Form a diamond shape with thumbs and index fingers, keep elbows close, press up explosively.",
    primaryMuscle: "TRICEPS",
    secondaryMuscles: ["CHEST", "SHOULDERS"],
    equipment: "BODYWEIGHT",
    category: "PUSH",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "bodyweight-squat",
    name: "Bodyweight Squat",
    description: "Lower-body staple that develops quad strength and hip mobility.",
    instructions: "Feet shoulder-width, sit hips back and down, knees tracking toes, drive through full foot.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "HAMSTRINGS", "CORE"],
    equipment: "BODYWEIGHT",
    category: "LEGS",
    difficulty: "BEGINNER",
  },
  {
    slug: "jump-squat",
    name: "Jump Squat",
    description: "Power-focused squat variation for athletic conditioning.",
    instructions: "Squat down, explode upward, land softly with knees soft.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "CALVES", "CARDIO"],
    equipment: "BODYWEIGHT",
    category: "CONDITIONING",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "lunge",
    name: "Walking Lunge",
    description: "Unilateral leg work that builds balance and single-leg strength.",
    instructions: "Step forward, drop back knee toward the floor, drive off front heel.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    equipment: "BODYWEIGHT",
    category: "LEGS",
    difficulty: "BEGINNER",
  },
  {
    slug: "burpee",
    name: "Burpee",
    description: "Full-body conditioning movement.",
    instructions: "Squat, hands down, jump feet back to plank, push-up, jump feet in, vertical jump.",
    primaryMuscle: "FULL_BODY",
    secondaryMuscles: ["CARDIO", "CORE"],
    equipment: "BODYWEIGHT",
    category: "CONDITIONING",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "plank",
    name: "Front Plank",
    description: "Isometric core hold that builds anti-extension strength.",
    instructions: "Forearms under shoulders, body in straight line, brace ribs to hips.",
    primaryMuscle: "CORE",
    secondaryMuscles: ["SHOULDERS"],
    equipment: "MAT",
    category: "CORE",
    difficulty: "BEGINNER",
  },
  {
    slug: "side-plank",
    name: "Side Plank",
    description: "Lateral core engagement and obliques.",
    instructions: "Stack feet, lift hips, drive bottom elbow into floor, hold tall.",
    primaryMuscle: "CORE",
    secondaryMuscles: ["SHOULDERS"],
    equipment: "MAT",
    category: "CORE",
    difficulty: "BEGINNER",
  },
  {
    slug: "jumping-jack",
    name: "Jumping Jack",
    description: "Low-impact cardio warm-up.",
    instructions: "Jump feet wide as arms reach overhead, return to start.",
    primaryMuscle: "CARDIO",
    secondaryMuscles: ["CALVES", "SHOULDERS"],
    equipment: "BODYWEIGHT",
    category: "CONDITIONING",
    difficulty: "BEGINNER",
  },
  {
    slug: "mountain-climber",
    name: "Mountain Climber",
    description: "Core + conditioning combo.",
    instructions: "From plank, drive knees alternately to chest at a controlled pace.",
    primaryMuscle: "CORE",
    secondaryMuscles: ["CARDIO", "SHOULDERS"],
    equipment: "BODYWEIGHT",
    category: "CONDITIONING",
    difficulty: "BEGINNER",
  },
  {
    slug: "backpack-row",
    name: "Backpack Row",
    description: "Bent-over rowing using a loaded backpack — replaces dumbbells.",
    instructions: "Load 5-15kg books in a backpack, hinge at hips, row pack to belly.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS", "CORE"],
    equipment: "BACKPACK",
    category: "PULL",
    difficulty: "BEGINNER",
  },
  {
    slug: "backpack-goblet-squat",
    name: "Backpack Goblet Squat",
    description: "Loaded squat using a backpack held at chest.",
    instructions: "Hug pack to chest, squat to depth, drive up.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "CORE"],
    equipment: "BACKPACK",
    category: "LEGS",
    difficulty: "BEGINNER",
  },
  {
    slug: "band-pull-apart",
    name: "Band Pull-Apart",
    description: "Posture and upper-back warm-up.",
    instructions: "Hold band at shoulder height, pull apart by squeezing shoulder blades.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["SHOULDERS"],
    equipment: "RESISTANCE_BAND",
    category: "MOBILITY",
    difficulty: "BEGINNER",
  },
  {
    slug: "band-row",
    name: "Resistance Band Row",
    description: "Horizontal pulling pattern using a band anchor.",
    instructions: "Anchor band, pull handles to ribs, squeeze shoulder blades.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS"],
    equipment: "RESISTANCE_BAND",
    category: "PULL",
    difficulty: "BEGINNER",
  },
  {
    slug: "band-press",
    name: "Resistance Band Overhead Press",
    description: "Vertical pressing pattern with a band.",
    instructions: "Stand on band, press handles overhead.",
    primaryMuscle: "SHOULDERS",
    secondaryMuscles: ["TRICEPS"],
    equipment: "RESISTANCE_BAND",
    category: "PUSH",
    difficulty: "BEGINNER",
  },
  {
    slug: "pull-up",
    name: "Pull-Up",
    description: "King of vertical pulling.",
    instructions: "Hang from a bar, drive elbows down, chin over bar, lower with control.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS", "CORE"],
    equipment: "PULL_UP_BAR",
    category: "PULL",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    description: "Core control from a dead hang.",
    instructions: "Hang from bar, brace core, lift knees to chest.",
    primaryMuscle: "CORE",
    secondaryMuscles: ["FOREARMS"],
    equipment: "PULL_UP_BAR",
    category: "CORE",
    difficulty: "INTERMEDIATE",
  },
  // -----------------------  GYM / EQUIPMENT  -----------------------
  {
    slug: "barbell-back-squat",
    name: "Barbell Back Squat",
    description: "Compound leg builder.",
    instructions: "Bar across upper back, brace, descend to depth, drive through midfoot.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "HAMSTRINGS", "CORE"],
    equipment: "BARBELL",
    category: "STRENGTH",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "barbell-deadlift",
    name: "Conventional Deadlift",
    description: "Total-body posterior chain compound.",
    instructions: "Bar mid-foot, hinge to bar, grip, pull slack, push the floor away, lock out hips.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["HAMSTRINGS", "GLUTES", "CORE"],
    equipment: "BARBELL",
    category: "STRENGTH",
    difficulty: "ADVANCED",
  },
  {
    slug: "barbell-bench-press",
    name: "Barbell Bench Press",
    description: "Upper-body pressing standard.",
    instructions: "Eyes under bar, retract shoulder blades, touch chest, drive bar up and slightly back.",
    primaryMuscle: "CHEST",
    secondaryMuscles: ["TRICEPS", "SHOULDERS"],
    equipment: "BARBELL",
    category: "STRENGTH",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "barbell-overhead-press",
    name: "Standing Overhead Press",
    description: "Vertical pressing strength.",
    instructions: "Bar at front rack, brace abs and glutes, press straight overhead, finish under bar.",
    primaryMuscle: "SHOULDERS",
    secondaryMuscles: ["TRICEPS", "CORE"],
    equipment: "BARBELL",
    category: "STRENGTH",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "barbell-row",
    name: "Barbell Bent-Over Row",
    description: "Horizontal pulling compound.",
    instructions: "Hinge to ~45°, pull bar to lower ribs, control eccentric.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS"],
    equipment: "BARBELL",
    category: "HYPERTROPHY",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    description: "Unilateral pressing variation.",
    instructions: "Lie on bench, press dumbbells with neutral wrists, control descent.",
    primaryMuscle: "CHEST",
    secondaryMuscles: ["TRICEPS", "SHOULDERS"],
    equipment: "DUMBBELL",
    category: "HYPERTROPHY",
    difficulty: "BEGINNER",
  },
  {
    slug: "dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    description: "Unilateral pulling for lat thickness.",
    instructions: "Hand and knee on bench, row dumbbell to hip, squeeze lat.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS"],
    equipment: "DUMBBELL",
    category: "HYPERTROPHY",
    difficulty: "BEGINNER",
  },
  {
    slug: "dumbbell-rdl",
    name: "Dumbbell Romanian Deadlift",
    description: "Hamstring + glute hinge.",
    instructions: "Slight knee bend, push hips back, lower dumbbells along legs, drive hips forward.",
    primaryMuscle: "HAMSTRINGS",
    secondaryMuscles: ["GLUTES", "BACK"],
    equipment: "DUMBBELL",
    category: "HYPERTROPHY",
    difficulty: "BEGINNER",
  },
  {
    slug: "dumbbell-curl",
    name: "Dumbbell Biceps Curl",
    description: "Direct biceps work.",
    instructions: "Curl with elbows pinned, control negative.",
    primaryMuscle: "BICEPS",
    secondaryMuscles: ["FOREARMS"],
    equipment: "DUMBBELL",
    category: "HYPERTROPHY",
    difficulty: "BEGINNER",
  },
  {
    slug: "lat-pulldown",
    name: "Lat Pulldown",
    description: "Vertical pulling on the cable stack.",
    instructions: "Lean back slightly, drive elbows down and back, control return.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS"],
    equipment: "CABLE_MACHINE",
    category: "HYPERTROPHY",
    difficulty: "BEGINNER",
  },
  {
    slug: "leg-press",
    name: "Leg Press",
    description: "Machine compound for quads and glutes.",
    instructions: "Feet shoulder-width on platform, lower under control to ~90°, press without locking knees.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    equipment: "SMITH_MACHINE",
    category: "HYPERTROPHY",
    difficulty: "BEGINNER",
  },
  {
    slug: "kettlebell-swing",
    name: "Kettlebell Swing",
    description: "Explosive hip hinge for power and conditioning.",
    instructions: "Hike bell back, snap hips forward, float bell to shoulder height.",
    primaryMuscle: "GLUTES",
    secondaryMuscles: ["HAMSTRINGS", "BACK", "CARDIO"],
    equipment: "KETTLEBELL",
    category: "CONDITIONING",
    difficulty: "INTERMEDIATE",
  },
  {
    slug: "jump-rope",
    name: "Jump Rope",
    description: "Boxing-staple conditioning.",
    instructions: "Light bounce, wrists rotate the rope, stay tall.",
    primaryMuscle: "CARDIO",
    secondaryMuscles: ["CALVES", "FOREARMS"],
    equipment: "JUMP_ROPE",
    category: "CONDITIONING",
    difficulty: "BEGINNER",
  },
  // -----------------------  BOXING  -----------------------
  {
    slug: "shadow-boxing",
    name: "Shadow Boxing",
    description: "Foundational boxing drill — no equipment, focus on form.",
    instructions: "Stance check, throw clean 1-2s and combos with breathing and footwork for the round.",
    primaryMuscle: "FULL_BODY",
    secondaryMuscles: ["SHOULDERS", "CORE", "CARDIO"],
    equipment: "BODYWEIGHT",
    category: "BOXING",
    difficulty: "BEGINNER",
    isBoxing: true,
  },
  {
    slug: "heavy-bag-rounds",
    name: "Heavy Bag Rounds",
    description: "Bag work for power, conditioning and timing.",
    instructions: "Maintain stance, snap punches back, breathe out on every shot, vary combos.",
    primaryMuscle: "FULL_BODY",
    secondaryMuscles: ["SHOULDERS", "CORE", "CARDIO"],
    equipment: "PUNCHING_BAG",
    category: "BOXING",
    difficulty: "BEGINNER",
    isBoxing: true,
  },
  {
    slug: "footwork-ladder",
    name: "Footwork Ladder Drill",
    description: "Coordination, agility and ring movement.",
    instructions: "Stay on balls of feet, light steps, eyes up.",
    primaryMuscle: "CALVES",
    secondaryMuscles: ["CARDIO", "QUADS"],
    equipment: "BODYWEIGHT",
    category: "BOXING",
    difficulty: "BEGINNER",
    isBoxing: true,
  },
];

export async function seedExercises(prisma: PrismaClient) {
  for (const ex of EXERCISES) {
    await prisma.exercise.upsert({
      where: { slug: ex.slug },
      update: {
        name: ex.name,
        description: ex.description,
        instructions: ex.instructions,
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        category: ex.category,
        difficulty: ex.difficulty,
        isBoxing: ex.isBoxing ?? false,
      },
      create: {
        slug: ex.slug,
        name: ex.name,
        description: ex.description,
        instructions: ex.instructions,
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        category: ex.category,
        difficulty: ex.difficulty,
        isBoxing: ex.isBoxing ?? false,
      },
    });
  }
  return EXERCISES.length;
}

export const EXERCISE_SLUGS = EXERCISES.map((e) => e.slug);
